config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'

  get 'charges/create'

  get 'search/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products, only: [:index, :show] do
    collection do
      post :clear_shopping_cart
    end

    member do
      post :add_to_cart
      post :remove_from_cart
    end
  end

  resources :categories, only: [:show]
  resources :customers, only: [:create]

  get 'search', to: 'search#index', as: 'search'

  resources :carts
  get 'carts/clear_shopping_cart', to: 'carts#clear_shopping_cart'
  get 'carts/checkout', to: 'carts#checkout'
  get 'carts/checkout/process_payment', to: 'carts#process_payment', as: 'carts/process_payment'

  resources :charges, only: [:new, :create]

  root to: 'products#index'
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :initialize_session
  before_action :load_shopping_cart
  before_action :load_subtotal

  def show
    @categories = Category.all
    @products = []

    @shopping_cart_items.each do |product_hash|

      @products << { product: Product.find(product_hash["id"]), quantity: product_hash["quantity"] }
    end

  end

  def checkout
    @categories = Category.all
    @provinces = Province.all

    @customer = Customer.new
  end

  def process_payment
    @categories = Category.all
    # TODO: continue from here
  end

  private

  def initialize_session
    session[:shopping_cart] ||= []
  end

  def load_shopping_cart
    @shopping_cart_items = session[:shopping_cart]
  end

  def load_subtotal
    @subtotal = 0
    @shopping_cart_items.each do |product|
      @subtotal += Product.find(product["id"]).price
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :initialize_session
  before_action :load_shopping_cart
  before_action :load_subtotal

  def index
    @categories = Category.all

    insert_quantities
  end

  # aka the Checkout section
  def show
    @categories = Category.all
    @provinces = Province.all

    @customer = Customer.new
  end

  def update
    @categories = Category.all

    # Receives the POST ID and quantity
    id = params[:id].to_i
    entered_quantity = params[:q].to_i

    # Updates the product quantity within the cart session
    # for the product with the given ID
    session[:shopping_cart].each do |product_hash|
      if product_hash["id"] == id
        product_hash["quantity"] = entered_quantity
      end
    end

    insert_quantities
  end

  # remove_from_cart is in the products controller

  # clear_shopping_cart is in the products controller

  def process_payment
    @categories = Category.all
    # @amount = 500 # $5.00 in cents
    @amount = ((session[:subtotal].to_f * session[:taxrate].to_f / 100) + session[:subtotal].to_f) * 100
    @description = 'Description of Charge'
  end

  private

  def initialize_session
    session[:shopping_cart] ||= []
  end

  def load_shopping_cart
    @shopping_cart_items = session[:shopping_cart]
  end

  def load_subtotal
    @subtotal = 0
    @shopping_cart_items.each do |product|
      @subtotal += (Product.find(product["id"]).price * product["quantity"].to_i)
    end
  end

  def insert_quantities
    @products = []
    @shopping_cart_items.each do |product_hash|
      @products << { product: Product.find(product_hash["id"]), quantity: product_hash["quantity"] }
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/cart/show.html.erb
<h1>Shopping Cart</h1>

<% @products.each do |product| %>

  <div class="row">
    <div class="col-sm-3">
      <%= image_tag product[:product].image, size: '200' %>
    </div>
    <div class="col-sm-9">
      <p><%= link_to product[:product].name, product[:product] %></p>
      <p>
        <strong>Price:</strong>
        <%= number_to_currency(product[:product].price)  %>
      </p>
      <p>
        <strong>Quantity:</strong>
        <%= product[:quantity] %>
      </p>
      <p>
        <strong>Category:</strong>
        <%=  link_to product[:product].category.name, product[:product].category  %>
      </p>
      <%= link_to 'Remove item from cart', remove_from_cart_product_path(product[:product]), method: :post %>
    </div>
  </div>
<% end %>

<% if @shopping_cart_items.empty? %>
  <p>You have no items in your shopping cart.</p>
<% else %>
  <h2>Subtotal: <%= number_to_currency(@subtotal) %></h2>
  <p><%= link_to 'Proceed to Checkout', cart_checkout_path %></p>
  <p><%= link_to 'Clear shopping cart', clear_shopping_cart_products_path, method: :post %></p>
<% end %>