config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'

  get 'charges/create'

  get 'search/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products, only: [:index, :show] do
    collection do
      post :clear_shopping_cart
    end

    member do
      post :add_to_cart
      post :remove_from_cart
    end
  end

  resources :categories, only: [:show]
  resources :customers, only: [:create]

  get 'search', to: 'search#index', as: 'search'

  resources :carts
  get 'carts/clear_shopping_cart', to: 'carts#clear_shopping_cart'
  get 'carts/checkout', to: 'carts#checkout'
  get 'carts/checkout/process_payment', to: 'carts#process_payment', as: 'carts/process_payment'

  resources :charges, only: [:new, :create]

  root to: 'products#index'
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :initialize_session
  before_action :load_shopping_cart
  before_action :load_subtotal

  def show
    @categories = Category.all
    @products = []

    @shopping_cart_items.each do |product_hash|

      @products << { product: Product.find(product_hash["id"]), quantity: product_hash["quantity"] }
    end

  end

  def checkout
    @categories = Category.all
    @provinces = Province.all

    @customer = Customer.new
  end

  def process_payment
    @categories = Category.all
    # TODO: continue from here
  end

  private

  def initialize_session
    session[:shopping_cart] ||= []
  end

  def load_shopping_cart
    @shopping_cart_items = session[:shopping_cart]
  end

  def load_subtotal
    @subtotal = 0
    @shopping_cart_items.each do |product|
      @subtotal += Product.find(product["id"]).price
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :initialize_session
  before_action :load_shopping_cart
  before_action :load_subtotal

  def index
    @categories = Category.all

    insert_quantities
  end

  # aka the Checkout section
  def show
    @categories = Category.all
    @provinces = Province.all

    @customer = Customer.new
  end

  def update
    @categories = Category.all

    # Receives the POST ID and quantity
    id = params[:id].to_i
    entered_quantity = params[:q].to_i

    # Updates the product quantity within the cart session
    # for the product with the given ID
    session[:shopping_cart].each do |product_hash|
      if product_hash["id"] == id
        product_hash["quantity"] = entered_quantity
      end
    end

    insert_quantities
  end

  # remove_from_cart is in the products controller

  # clear_shopping_cart is in the products controller

  def process_payment
    @categories = Category.all
    # @amount = 500 # $5.00 in cents
    @amount = ((session[:subtotal].to_f * session[:taxrate].to_f / 100) + session[:subtotal].to_f) * 100
    @description = 'Description of Charge'
  end

  private

  def initialize_session
    session[:shopping_cart] ||= []
  end

  def load_shopping_cart
    @shopping_cart_items = session[:shopping_cart]
  end

  def load_subtotal
    @subtotal = 0
    @shopping_cart_items.each do |product|
      @subtotal += (Product.find(product["id"]).price * product["quantity"].to_i)
    end
  end

  def insert_quantities
    @products = []
    @shopping_cart_items.each do |product_hash|
      @products << { product: Product.find(product_hash["id"]), quantity: product_hash["quantity"] }
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/checkout.html.erb
<h1>Checkout</h1>
<p>Subtotal: <%= number_to_currency(@subtotal) %></p>

<%= form_for @customer do |f| %>

  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :email %>:
  <%= f.text_field :email %><br />

  <%= f.label :address %>:
  <%= f.text_field :address %><br />

  <%= f.label :city %>:
  <%= f.text_field :city %><br />

  <%= f.label :postalCode %>:
  <%= f.text_field :postalCode %><br />

  <%= f.label :province_id %>:
  <%= f.collection_select(:province_id, Province.all, :id, :name) %><br />

  <%= f.submit %>
<% end %>

app/views/carts/index.html.erb
<h1>Shopping Cart</h1>

<% @products.each do |product| %>

  <div class="row">
    <div class="col-sm-3">
      <%= image_tag product[:product].image, size: '200' %>
    </div>
    <div class="col-sm-9">
      <p><%= link_to product[:product].name, product[:product] %></p>
      <p>
        <strong>Price:</strong>
        <%= number_to_currency(product[:product].price)  %>
      </p>
      <p>
        <%= form_tag(cart_path(id: product[:product].id), method: "patch") do %>
          <%= label_tag(:q, "Quantity:") %>
          <%= text_field_tag(:q, product[:quantity]) %>
          <%= submit_tag("Update") %>
        <% end %>
      </p>
      <%= link_to 'Remove item from cart', remove_from_cart_product_path(product[:product]), method: :post %>
    </div>
  </div>
<% end %>

<% if @shopping_cart_items.empty? %>
  <p>You have no items in your shopping cart.</p>
<% else %>
  <h2>Subtotal: <%= number_to_currency(@subtotal) %></h2>
  <p><%= link_to 'Proceed to Checkout', carts_checkout_path %></p>
  <p><%= link_to 'Clear shopping cart', clear_shopping_cart_products_path, method: :post %></p>
<% end %>

app/views/carts/processPayment.html.erb
<h1>Process Payment!</h1>

app/views/carts/process_payment.html.erb
<h1>Process Payment!</h1>

<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Grand Total: <%= number_to_currency(@amount / 100) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="<%= @description %>"
          data-amount="<%= @amount %>"
          data-locale="auto"></script>
<% end %>

<p>Things left to do:</p>
<ul>
  <li>implement stripe</li>
  <li>Set the Order status to paid</li>
</ul>

<h3>Subtotal: <%= number_to_currency(session[:subtotal]) %></h3>
<h3>Taxes: <%= number_to_currency(session[:taxrate].to_f * session[:subtotal].to_f / 100) %></h3>
<h2>Grand total: <%= number_to_currency(@amount / 100) %></h2>

<%= link_to "Link to home page", root_url %>

app/views/carts/show.html.erb
<h1>Checkout</h1>
<p>Subtotal: <%= number_to_currency(@subtotal) %></p>

<%= form_for @customer do |f| %>

  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :email %>:
  <%= f.text_field :email %><br />

  <%= f.label :address %>:
  <%= f.text_field :address %><br />

  <%= f.label :city %>:
  <%= f.text_field :city %><br />

  <%= f.label :postalCode %>:
  <%= f.text_field :postalCode %><br />

  <%= f.label :province_id %>:
  <%= f.collection_select(:province_id, Province.all, :id, :name) %><br />

  <%= f.submit %>
<% end %>