config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'

  get 'charges/create'

  get 'search/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products, only: [:index, :show] do
    collection do
      post :clear_shopping_cart
    end

    member do
      post :add_to_cart
      post :remove_from_cart
    end
  end

  resources :categories, only: [:show]
  resources :customers, only: [:create]

  get 'search', to: 'search#index', as: 'search'

  resources :carts
  get 'carts/clear_shopping_cart', to: 'carts#clear_shopping_cart'
  get 'carts/checkout', to: 'carts#checkout'
  get 'carts/checkout/process_payment', to: 'carts#process_payment', as: 'carts/process_payment'

  resources :charges, only: [:new, :create]

  root to: 'products#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, :email, :address, :city, :postalCode, presence: true
  validates :email, uniqueness: true

  belongs_to :province

  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  validates :subtotal, :purchaseTaxRate, presence: true

  belongs_to :status
  belongs_to :customer

  has_many :purchases

  # def subtotal(id)
  #   total = 0
  #   Purchase.where(order_id: id).each do |purchase|
  #     total += purchase.purchaseUnitPrice * purchase.quantity
  #   end
  #   total
  # end
  #
  # def taxes(id)
  #   total = subtotal(id)
  #   tax = Order.find(id).customer.province.taxRate
  #   total * tax
  # end
  #
  # def grand_total(id)
  #   subtotal(id) + taxes(id)
  # end

end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price, presence: true
  validates :name, uniqueness: true

  belongs_to :category

  has_many :purchases

  mount_uploader :image, ImageUploader
end

app/models/province.rb
class Province < ApplicationRecord
  validates :name, :taxRate, presence: true
  validates :name, uniqueness: true

  has_many :customers
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  validates :quantity, :purchaseUnitPrice, presence: true
  validates :quantity, :purchaseUnitPrice, uniqueness: true

  belongs_to :product
  belongs_to :order
end

app/models/status.rb
class Status < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :orders
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :initialize_session
  before_action :load_shopping_cart
  before_action :load_subtotal

  def show
    @categories = Category.all
    @products = []

    @shopping_cart_items.each do |product_hash|

      @products << { product: Product.find(product_hash["id"]), quantity: product_hash["quantity"] }
    end

  end

  def checkout
    @categories = Category.all
    @provinces = Province.all

    @customer = Customer.new
  end

  def process_payment
    @categories = Category.all
    # TODO: continue from here
  end

  private

  def initialize_session
    session[:shopping_cart] ||= []
  end

  def load_shopping_cart
    @shopping_cart_items = session[:shopping_cart]
  end

  def load_subtotal
    @subtotal = 0
    @shopping_cart_items.each do |product|
      @subtotal += Product.find(product["id"]).price
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :initialize_session
  before_action :load_shopping_cart
  before_action :load_subtotal

  def index
    @categories = Category.all

    insert_quantities
  end

  # aka the Checkout section
  def show
    @categories = Category.all
    @provinces = Province.all

    @customer = Customer.new
  end

  def update
    @categories = Category.all

    # Receives the POST ID and quantity
    id = params[:id].to_i
    entered_quantity = params[:q].to_i

    # Updates the product quantity within the cart session
    # for the product with the given ID
    session[:shopping_cart].each do |product_hash|
      if product_hash["id"] == id
        product_hash["quantity"] = entered_quantity
      end
    end

    insert_quantities
  end

  # remove_from_cart is in the products controller

  # clear_shopping_cart is in the products controller

  def process_payment
    @categories = Category.all
    # @amount = 500 # $5.00 in cents
    @amount = ((session[:subtotal].to_f * session[:taxrate].to_f / 100) + session[:subtotal].to_f) * 100
    @description = 'Description of Charge'
  end

  private

  def initialize_session
    session[:shopping_cart] ||= []
  end

  def load_shopping_cart
    @shopping_cart_items = session[:shopping_cart]
  end

  def load_subtotal
    @subtotal = 0
    @shopping_cart_items.each do |product|
      @subtotal += (Product.find(product["id"]).price * product["quantity"].to_i)
    end
  end

  def insert_quantities
    @products = []
    @shopping_cart_items.each do |product_hash|
      @products << { product: Product.find(product_hash["id"]), quantity: product_hash["quantity"] }
    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @categories = Category.all
    @amount = 500 # $5.00 in cents
    @description = 'Description of Charge'
  end

  def create
    @categories = Category.all

    # Amount in cents
    amount = 500 # TODO: Change this to the actual amount (and also change the description!)

    @customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    @charge = Stripe::Charge.create(
      customer: @customer.id,
      amount: amount,
      description: 'Rails Stripe customer',
      currency: 'cad'
    )

    # @customer.id will have the Stripe customer id, store it within the Order table
    # @charge.paid returns a boolean depending if the charge was successful

    if @charge.paid && @charge.amount == (session[:subtotal] * 100)
      paidOrder = Order.find(session[:customer_id])
      paidOrder.stripePayment = @charge.id
      paidOrder.stripeCustomer = @customer.id
      paidOrder.status = Status.find_by(name: "paid")
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @search_terms = params[:q]
    @products = Product.where("name LIKE '%#{@search_terms}%'")

    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kaori Music</title>
    <%= csrf_meta_tags %>

    <link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <div class="header">
    <h2 class="col-sm-8"><%= link_to 'Kaori Music', root_url %></h2>

    <div class="search, col-sm-4">
      <%= link_to "Shopping Cart [#{session[:shopping_cart].count}]", carts_path %>
      <%= form_tag(search_path, method: "get") do %>
        <%= label_tag(:q, "Search products for:") %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search") %>
      <% end %>
    </div>
  </div>

  <!-- NavigationBar -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <li ><%= link_to 'Kaori Music', root_url %></li>
        <% @categories.each do |category| %>
          <li><%= link_to category.name, category %></li>
        <% end %>
        <li><%= link_to '- New! -', root_url %></li>
        <li><%= link_to '- Updated! -', root_url %></li>
      </ul>
    </div>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_show_products.html.erb
<div class="container">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-sm-3 test row-eq-height">
        <%= image_tag product.image, size: '200' %>
        <p><%= link_to product.name, product %></p>
        <p>
          <strong>Price:</strong>
          <%= number_to_currency(product.price)  %>
        </p>
        <% unless controller_name == 'categories' %>
          <p>
            <strong>Category:</strong>
            <%=  link_to product.category.name, product.category  %>
          </p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>